[package]
name = "perf-event-rs"
version = "0.0.0"
edition = "2021"
description = "Linux perf event in Rust without unsafe"
license = "MIT"
repository = "git@github.com:OptimatistOpenSource/perf-event-rs.git"
keywords = ["binding", "event", "perf"]
categories = ["API bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
