[package]
name = "perf-event-rs"
version = "0.0.0"
edition = "2021"
description = "Linux perf event in Rust without unsafe"
license = "MIT"
repository = "https://github.com/OptimatistOpenSource/perf-event-rs.git"
keywords = ["binding", "event", "perf"]
categories = ["API bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
libc = "0.2.148"
page_size = "0.6.0"
