#[cfg(feature = "linux-4.1")]
pub mod aux;
pub mod aux_output_hw_id;
#[cfg(feature = "linux-5.1")]
pub mod bpf_event;
#[cfg(feature = "linux-5.7")]
pub mod cgroup;
pub mod comm;
pub mod exit;
pub mod fork;
#[cfg(feature = "linux-4.1")]
pub mod intrace_start;
#[cfg(feature = "linux-5.1")]
pub mod ksymbol;
pub mod lost;
#[cfg(feature = "linux-4.2")]
pub mod lost_samples;
pub mod mmap;
#[cfg(feature = "linux-3.12")]
pub mod mmap2;
#[cfg(feature = "linux-4.12")]
pub mod namespaces;
pub mod read;
pub mod sample;
#[cfg(feature = "linux-4.3")]
pub mod switch;
#[cfg(feature = "linux-4.3")]
pub mod switch_cpu_wide;
#[cfg(feature = "linux-5.9")]
pub mod text_poke;
pub mod throttle;
pub mod unthrottle;
