name: Build / Development (auto feature)

on:
  push:
    branches:
      - '*'
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  build-dev:
    name: ${{ matrix.target.alias }}
    runs-on: ${{ matrix.target.os }}

    strategy:
      fail-fast: false
      matrix:
        target:
          # TODO: Build in ubuntu-20.04 from GitHub Actions fails due to missing some definitions in `linux/version.h`
          #- { os: ubuntu-20.04, triple: x86_64-unknown-linux-gnu , alias: amd64-gnu-ubuntu-20.04 }
          #- { os: ubuntu-20.04, triple: x86_64-unknown-linux-musl, alias: amd64-musl-ubuntu-20.04 }
          - { os: ubuntu-22.04, triple: x86_64-unknown-linux-gnu , alias: amd64-gnu-ubuntu-22.04 }
          - { os: ubuntu-22.04, triple: x86_64-unknown-linux-musl, alias: amd64-musl-ubuntu-22.04 }

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: 1.75.0
          components: rustfmt, clippy

      - name: Show environment information
        shell: bash
        run: |
          cargo -V
          cargo clippy -V
          cargo fmt -- -V
          rustc -V
          uname -a

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.target.alias }}

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1.3.1
        with:
          packages: musl-tools
          version: 1.0

      - name: Setup musl-tools
        if: matrix.target.triple == 'x86_64-unknown-linux-musl'
        shell: bash
        run: sudo apt -y install musl-tools

      - name: Add target
        uses: ./.github/actions/add-target
        with:
          target: ${{ matrix.target.triple }}

      - name: Generate version
        id: gen-version
        shell: bash
        run: echo 'VERSION=0.0.0-${{ github.sha }}' >> $GITHUB_OUTPUT

      - name: Replace version
        uses: ./.github/actions/replace-version
        with:
          version: ${{ steps.gen-version.outputs.VERSION }}

      - name: Run build
        uses: ./.github/actions/build
        with:
          target: ${{ matrix.target.triple }}
          feature: auto
          release: false

      - name: Run check
        uses: ./.github/actions/check
        with:
          target: ${{ matrix.target.triple }}
          feature: auto

      # TODO: Some tests will fail in GitHub Actions environment